### ISSUE TITLE
doesn't do anything

### ISSUE THREAD

**Issue by vv111y** [robert-wallis/docker-intellij-ce#2]
Starts then immediately terminates. No information given.

**Comment by vv111y** [comment]
update, it's now:
```config path /home/developer/.IdealC15/config is invalid. if you have modified the idea.config.path property please make sure it is correct otherwise please re-install the IDE ```

**Comment by vv111y** [comment]
update2:
Running Container as root on host works. Don't like the lower security, but at least it runs.

**Comment by robert-wallis** [comment]
Great to know! Thanks for following up!
